apiVersion: v1
kind: Service
metadata:
  name: hostinfo-springboot
  namespace: hostinfo-springboot
  labels:
    app: hostinfo-springboot
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: hostinfo-springboot
  sessionAffinity: None
