apiVersion: v1
kind: ConfigMap
metadata:
  name: hostinfo-helidon-config
  namespace: hostinfo-helidon
data:
  APPLICATION_NAME: "Host Information Service"
  HELIDON_ENVIRONMENT: "prod"
  SERVER_PORT: "8081"
  SERVER_CONTEXT_PATH: "/hostinfo"
  JAVA_OPTS: "-Xmx512m -Xms256m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
