apiVersion: v1
kind: Service
metadata:
  name: hostinfo-helidon
  namespace: hostinfo-helidon
  labels:
    app: hostinfo-helidon
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: hostinfo-helidon
  sessionAffinity: None
