apiVersion: v1
kind: ConfigMap
metadata:
  name: hostinfo-micronaut-config
  namespace: hostinfo-micronaut
data:
  APPLICATION_NAME: "Host Information Service"
  MICRONAUT_ENVIRONMENTS: "prod"
  MICRONAUT_SERVER_PORT: "8082"
  MICRONAUT_SERVER_SERVLET_CONTEXT_PATH: "/hostinfo"
  JAVA_OPTS: "-Xmx512m -Xms256m -XX:+UseContainerSupport"
