apiVersion: v1
kind: Service
metadata:
  name: hostinfo-micronaut
  namespace: hostinfo-micronaut
  labels:
    app: hostinfo-micronaut
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: hostinfo-micronaut
  sessionAffinity: None
