apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hostinfo-helidon
  namespace: hostinfo-helidon
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: wlsoke.alquinta.xyz
    http:
      paths:
      - path: /helidon
        pathType: Prefix
        backend:
          service:
            name: hostinfo-helidon
            port:
              number: 8081
