apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hostinfo-springboot
  namespace: hostinfo-springboot
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: wlsoke.alquinta.xyz
    http:
      paths:
      - path: /springboot
        pathType: Prefix
        backend:
          service:
            name: hostinfo-springboot
            port:
              number: 8080
